#cloud-config
package_upgrade: true
# TODO: rsyslog
chef:
  install_type: omnibus
  exec: true
  ssl_verify_mode: :verify_peer
  node_name: "${hostname}"
  server_url: "${chef_server_url}"
  environment: "${environment}"
  run_list:
  - "role[${role}]"
